# Basic
title: Liu's Den
subtitle:  人格的完善是本, 财富的确立是末.

welcome_message: 突破电脑特权, 创造艺术之美.
description: hi 嗨，我是柳川 (@LiuChuan_)，一名来自中国的 iOS / macOS / Python 开发者。<p>正在修行，探求创意之源。</p>There is no perfect system , only undiscovered vulnerabilities.
creator: <a href="https://twitter.com/LiuChuan_">@LiuChuan_</a>



#url: "http://liuchuanweb.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: 'https://github.com/DevLiuSir'}
    - {title: 关于, description: My Projects, url: 'https://DevLiuSir.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: LiuChuan77
    github: DevLiuSir
    twitter: LiuChuan_
    Facebook: ImDevLiuSir/
   # gplus: 107108267983477358170
    mail: liuchuan910927@hotmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
